### ISSUE TITLE
Spec is more lax than packager

### ISSUE THREAD

**Issue by layday** [ogri-la/release.json-specification#4]
Properties which have always been emitted by packager (`nolib`, `interface`) are optional and flavors which are not emitted by packager (the `flavor-alias` array) are allowed.  I assume this is to accommodate some of the more exotic `release.json`s found in the wild, but these are few and far between I find, and it might make more sense to poke their authors to fix them.  In addition, add-on managers like my own and AcidWeb's are probably not in a position to parse these stripped-down metadata files, so we'd need some buy-in from the add-on manager folk if the spec should be more forgiving than what's currently implemented.

**Comment by layday** [comment]
> Could you open a new issue with an example using comma separated `interface` values?

Comma-separated interfaces values are in TOC files.  In `release.json`, these will be split up so that you might have multiple interfaces mapping to the same flavor.  I don't believe the spec will change.

**Comment by torkus** [comment]
That's brilliant, I must have misread your comment the other day.
